version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8-aaa
    versions:
    - 0.11.2
  - dependency-name: pip-tools
    versions:
    - 6.0.1
    - 6.1.0
  - dependency-name: yamllint
    versions:
    - 1.26.1
  - dependency-name: pre-commit
    versions:
    - 2.11.1
    - 2.12.0
  - dependency-name: flake8-annotations
    versions:
    - 2.6.1
    - 2.6.2
  - dependency-name: flake8-pytest-style
    versions:
    - 1.4.1
  - dependency-name: flake8-bugbear
    versions:
    - 21.3.1
    - 21.3.2
    - 21.4.3
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.1
    - 2.7.3
  - dependency-name: pyflakes
    versions:
    - 2.3.1
  - dependency-name: flake8-comprehensions
    versions:
    - 3.4.0
  - dependency-name: flake8-docstrings
    versions:
    - 1.6.0
